pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test

  publish:
    image: plugins/docker
    username: rwolski
    password: beasty87
    email: rwolski@gmail.com
    repo: rwolski/test
    tags: latest
